# Query 1
SELECT P.PAT_AGE AS Patient_Age, DP.POL_PREMIUM AS Policy_Premium, 
CASE 
	WHEN DP.POL_PREMIUM > 1200 THEN 'High'
    WHEN DP.POL_PREMIUM > 800 AND DP.POL_PREMIUM <= 1200 THEN 'Medium'
    WHEN DP.POL_PREMIUM <= 800 THEN 'Low'
END AS Premium_Profile
FROM PATIENT AS P INNER JOIN INSURANCE AS I ON P.POL_ID = I.POL_ID INNER JOIN DUR_PREMIUM AS DP ON I.POL_ID = DP.POL_ID;

# Query 2
SELECT P.PAT_ID, DR.DRUGS_DISEASE_TREATED 
FROM PATIENT AS P INNER JOIN PRESCRIPTION AS PRES ON P.PAT_ID = PRES.PAT_ID 
INNER JOIN PRESCRIPTION_LINES AS PRES_LINE ON PRES.RX_ID = PRES_LINE.RX_ID 
INNER JOIN DRUGS AS DR ON PRES_LINE.DRUG_ID = DR.DRUG_ID;

# QUERY 3
SELECT COUNT(PRES.RX_ID) AS Total_Num_Pres, ROUND(SUM(SUB.RX_TOTAL), 2) AS Total_Price, 
ROUND(AVG(SUB.RX_TOTAL),2) AS Average_Price, MIN(SUB.RX_TOTAL) AS Min_Price, MAX(SUB.RX_TOTAL) AS Max_Price 
FROM PRESCRIPTION AS PRES JOIN SUBTOT_TAX_TOT AS SUB ON PRES.RX_ID = SUB.RX_ID;

# QUERY 4
SELECT METHOD_OF_ADMIN, COUNT(METHOD_OF_ADMIN) as "Times Prescribed" FROM PRESCRIPTION_LINES NATURAL JOIN DRUGS GROUP BY METHOD_OF_ADMIN;

# QUERY 5
SELECT DRUG_NAME, RX_LINE_PRICE as "Price in $" FROM PRESCRIPTION_LINES NATURAL JOIN DRUGS;

# QUERY 6
SELECT PHY_SPECIALIZATION, DRUGS_DISEASE_TREATED FROM PHYSICIAN NATURAL JOIN PRESCRIPTION NATURAL JOIN PRESCRIPTION_LINES NATURAL JOIN DRUGS;

# QUERY 7
SELECT MANUF_NAME, DRUG_NAME, SUM(RX_LINE_QUANTITY) as "Quantity Sold" FROM PRESCRIPTION_LINES NATURAL JOIN MAKES NATURAL JOIN DRUGS GROUP BY MANUF_NAME,DRUG_NAME;

# QUERY 8
SELECT SUM(POL_PREMIUM) as "Total Income" FROM PATIENT NATURAL JOIN DUR_PREMIUM;

# QUERY 9
SELECT POL_NAME, Count(*) as "Number of People" FROM PATIENT as P NATURAL JOIN INSURANCE as I GROUP BY P.POL_ID;


