# Query 1
SELECT P.PAT_AGE AS 'Patient\'s Age', DP.POL_PREMIUM AS 'Policy Premiums', 
CASE 
	WHEN DP.POL_PREMIUM > 1200 THEN 'High'
    WHEN DP.POL_PREMIUM > 800 AND DP.POL_PREMIUM <= 1200 THEN 'Medium'
    WHEN DP.POL_PREMIUM <= 800 THEN 'Low'
END AS 'Premium Profile'
FROM PATIENT AS P INNER JOIN INSURANCE AS I ON P.POL_ID = I.POL_ID INNER JOIN DUR_PREMIUM AS DP ON I.POL_ID = DP.POL_ID;

# Query 2
SELECT P.PAT_ID AS 'Patient IDs', DR.DRUGS_DISEASE_TREATED AS 'Diseases'
FROM PATIENT AS P INNER JOIN PRESCRIPTION AS PRES ON P.PAT_ID = PRES.PAT_ID 
INNER JOIN PRESCRIPTION_LINES AS PRES_LINE ON PRES.RX_ID = PRES_LINE.RX_ID 
INNER JOIN DRUGS AS DR ON PRES_LINE.DRUG_ID = DR.DRUG_ID;

# QUERY 3
SELECT COUNT(PRES.RX_ID) AS "Total Number of Prescriptions", 
ROUND(SUM(SUB.RX_TOTAL), 2) AS "Total Price", ROUND(AVG(SUB.RX_TOTAL),2) AS 
"Average Price", MIN(SUB.RX_TOTAL) AS "Min Price", MAX(SUB.RX_TOTAL) AS 
"Max Price" FROM PRESCRIPTION AS PRES JOIN SUBTOT_TAX_TOT AS SUB ON PRES.RX_ID = SUB.RX_ID;

# QUERY 4
SELECT DISTINCT METHOD_OF_ADMIN, COUNT(METHOD_OF_ADMIN) FROM DRUGS NATURAL JOIN PRESCRIPTION_LINES 
GROUP BY METHOD_OF_ADMIN ORDER BY COUNT(RX_LINE_PRICE) DESC LIMIT 1;

# QUERY 5
SELECT DRUG_NAME AS 'Drugs', RX_LINE_PRICE AS 'Price' FROM PRESCRIPTION_LINES NATURAL JOIN DRUGS 
WHERE RX_LINE_PRICE IN (SELECT MIN(RX_LINE_PRICE) FROM PRESCRIPTION_LINES) OR 
RX_LINE_PRICE IN (SELECT MAX(RX_LINE_PRICE) FROM PRESCRIPTION_LINES);

# QUERY 6
SELECT PHY_SPECIALIZATION AS 'Physician\'s Specialization', DRUGS_DISEASE_TREATED AS 'Diseases Treated' FROM PHYSICIAN NATURAL JOIN PRESCRIPTION 
NATURAL JOIN PRESCRIPTION_LINES NATURAL JOIN DRUGS ORDER BY PHY_SPECIALIZATION, DRUGS_DISEASE_TREATED;

# QUERY 7
SELECT MANUF_NAME AS 'Manufacturers', DRUG_NAME AS 'Drugs' , SUM(RX_LINE_QUANTITY) as "Quantity Sold" FROM PRESCRIPTION_LINES NATURAL JOIN MAKES NATURAL JOIN DRUGS 
GROUP BY MANUF_NAME,DRUG_NAME ORDER BY MANUF_NAME, DRUG_NAME, SUM(RX_LINE_QUANTITY);

# QUERY 8
SELECT SUM(POL_PREMIUM) as "Total Income of Insurance ($)" FROM PATIENT NATURAL JOIN DUR_PREMIUM;

# QUERY 9
SELECT POL_NAME AS "Policy", Count(*) as "Number of People enrolled" FROM PATIENT as P NATURAL JOIN INSURANCE as I GROUP BY P.POL_ID ORDER BY COUNT(*) DESC LIMIT 1;

# QUERY 10
SELECT DISTINCT RX_TAX AS 'Tax', PHARM_ADDRESS AS 'Location' FROM PRESCRIPTION NATURAL JOIN PHARMACY; 
